#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
RUN_SH="$ROOT_DIR/run.sh"
PRODUCTION_APP_BUNDLE="/Applications/ide.app"
BIN_DIR="${IDE_CLI_BIN_DIR:-$HOME/.local/bin}"
IDE_COMMAND_PATH="$BIN_DIR/ide"
IDE_DEV_COMMAND_PATH="$BIN_DIR/ide-dev"

if [ ! -x "$RUN_SH" ]; then
  echo "run.sh must be executable before installing the ide command." >&2
  exit 1
fi

mkdir -p "$BIN_DIR"

install_generated_launcher() {
  local command_path="$1"
  local app_bundle="$2"

  if [ -e "$command_path" ] || [ -L "$command_path" ]; then
    if [ "${IDE_CLI_FORCE:-0}" != "1" ] &&
      [ ! -L "$command_path" ] &&
      ! grep -q "Generated by ide/scripts/install-cli-command.sh" "$command_path" 2>/dev/null; then
      echo "$command_path already exists and was not generated by this installer." >&2
      echo "Set IDE_CLI_FORCE=1 to replace it." >&2
      exit 1
    fi
    rm -f "$command_path"
  fi

  cat >"$command_path" <<EOF
#!/usr/bin/env bash
# Generated by ide/scripts/install-cli-command.sh
set -euo pipefail

APP_BUNDLE="$app_bundle"
APP_BINARY="\$APP_BUNDLE/Contents/MacOS/ide"

if [ ! -d "\$APP_BUNDLE" ]; then
  echo "ide app bundle was not found: \$APP_BUNDLE" >&2
  exit 1
fi

if [ ! -x "\$APP_BINARY" ]; then
  echo "ide app binary was not found: \$APP_BINARY" >&2
  exit 1
fi

running_app_reachable() {
  curl -fsS --max-time 1 "http://127.0.0.1:17877/api/codex-mcp" >/dev/null 2>&1
}

activate_running_app() {
  if command -v osascript >/dev/null 2>&1; then
    osascript -e 'tell application id "com.gordonbeeming.ide" to activate' >/dev/null 2>&1 && return 0
    osascript -e 'tell application "ide" to activate' >/dev/null 2>&1 && return 0
  fi
  open -b "com.gordonbeeming.ide" >/dev/null 2>&1 || true
}

# Percent-encodes a path for the /browse?path= query string (spaces, etc). Pure bash
# so browse doesn't need curl's --data-urlencode just to build a URL.
url_encode() {
  # LC_ALL=C forces byte-wise iteration regardless of the caller's locale, and the
  # printf-based char-to-int conversion sign-extends bytes >= 0x80 (bash 3.2's builtin
  # printf, still the default /bin/bash on macOS) — masking with & 0xFF undoes that so
  # multi-byte UTF-8 paths percent-encode correctly.
  local LC_ALL=C
  local string="\$1"
  local length="\${#string}" i char
  for (( i = 0; i < length; i++ )); do
    char="\${string:i:1}"
    case "\$char" in
      [a-zA-Z0-9.~_-]) printf '%s' "\$char" ;;
      *) printf '%%%02X' "\$(( \$(printf '%d' "'\$char") & 0xFF ))" ;;
    esac
  done
}

resolve_absolute_path() {
  local path="\$1"
  if [ -d "\$path" ]; then
    (cd "\$path" && pwd -P)
  else
    printf '%s/%s' "\$(cd "\$(dirname "\$path")" && pwd -P)" "\$(basename "\$path")"
  fi
}

if [ "\$#" -eq 0 ] && running_app_reachable; then
  activate_running_app
  exit 0
fi

if [ "\${1:-}" = "browse" ]; then
  if [ "\$#" -lt 2 ] || [ ! -e "\$2" ]; then
    echo "Usage: ide browse <path>" >&2
    exit 1
  fi
  browse_path="\$(resolve_absolute_path "\$2")"
  browse_url="http://localhost:17877/browse?path=\$(url_encode "\$browse_path")"

  if ! running_app_reachable; then
    # Cold start: boot the bundle headless (no visible window — see lib.rs's
    # IDE_BROWSE_PATH handling) and wait for the HTTP server before hitting /browse.
    IDE_BROWSE_PATH="\$browse_path" open "\$APP_BUNDLE" --args browse "\$browse_path" >/dev/null 2>&1
    attempts=0
    until running_app_reachable; do
      attempts=\$((attempts + 1))
      if [ "\$attempts" -ge 50 ]; then
        echo "ide browse: timed out waiting for the app to start" >&2
        exit 1
      fi
      sleep 0.2
    done
  fi

  # Foreground, not backgrounded: under cmux the \`open\` shim hands the URL to a
  # \`cmux browser open\` child, and if this wrapper exits first the child is orphaned,
  # loses its pane/session context, and the shim falls back to the system browser.
  # \`open\` returns as soon as it dispatches the URL, so foregrounding costs nothing.
  open "\$browse_url" >/dev/null 2>&1
  exit 0
fi

ARGS=()
for arg in "\$@"; do
  if [ -e "\$arg" ]; then
    if [ -d "\$arg" ]; then
      ARGS+=("\$(cd "\$arg" && pwd -P)")
    else
      arg_dir="\$(dirname "\$arg")"
      arg_name="\$(basename "\$arg")"
      ARGS+=("\$(cd "\$arg_dir" && pwd -P)/\$arg_name")
    fi
  else
    ARGS+=("\$arg")
  fi
done

if [ "\${#ARGS[@]}" -gt 0 ]; then
  if running_app_reachable; then
    "\$APP_BINARY" "\${ARGS[@]}" >/dev/null 2>&1 &
    exit 0
  fi
  open "\$APP_BUNDLE" --args "\${ARGS[@]}" >/dev/null 2>&1 &
else
  open "\$APP_BUNDLE" >/dev/null 2>&1 &
fi
EOF
  chmod 755 "$command_path"
}

install_link() {
  local command_path="$1"
  local target_path="$2"

  if [ -e "$command_path" ] || [ -L "$command_path" ]; then
    if [ "${IDE_CLI_FORCE:-0}" != "1" ] &&
      [ ! -L "$command_path" ] &&
      ! grep -q "Generated by ide/scripts/install-cli-command.sh" "$command_path" 2>/dev/null; then
      echo "$command_path already exists and was not generated by this installer." >&2
      echo "Set IDE_CLI_FORCE=1 to replace it." >&2
      exit 1
    fi
    rm -f "$command_path"
  fi

  ln -s "$target_path" "$command_path"
}

install_generated_launcher "$IDE_COMMAND_PATH" "$PRODUCTION_APP_BUNDLE"
install_link "$IDE_DEV_COMMAND_PATH" "$RUN_SH"

echo "Installed ide command at $IDE_COMMAND_PATH -> $PRODUCTION_APP_BUNDLE"
echo "Installed ide-dev command at $IDE_DEV_COMMAND_PATH -> $RUN_SH"
